on:
    push:
        branches:
            - main
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: sudo apt install -y llvm-11-dev clang-11 make
            - run: make
            - run: ./test.sh
